### ISSUE TITLE
lot number 20433633 repeat

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#23] opened 2020-07-27 11:10 UTC
For some reason this lot number (and it seems to be the only one) that is currently on the database, appears repeated four times on the main item page.
Can you check if this can be a problem? Did I book something wrong?

**Comment by kjthoward** [comment] 2020-07-27 11:16
Did you put in multiple lot numbers because there were multiple items??? If you enter more than "1" in the "Number received" box it just makes a X copies of that exact record, so all items need to have the same lot number as you only enter one lot number

**Comment by FlaviaMS** [comment] 2020-07-27 11:25
I did not put multiple lot number on any of the item, at least conscientiously.

**Comment by kjthoward** [comment] 2020-07-27 11:32
Just tried several times with the same, and different, information to what you had for that reagent and I can't seem to get it to reproduce the same error... I'm going to close this, but feel free to re-open if it happens again. I'll also manually change the lot number of those 3 items (J19X, J19R and J19W) to only have 1 lot number

**Closed by kjthoward** 2020-07-27 11:32 UTC

**Comment by FlaviaMS** [comment] 2020-07-27 11:33
Thank you
